---
- name: "Initial install and configuration"
  become: true
  hosts: centos7-test
  vars:
    postgresql_users:
      - name: ruby_user
        db: ruby_app
        password: testtesttest
        encrypted: true
    postgresql_databases:
      - name: ruby_app
        owner: ruby_user

  roles:
    - postgresql
