---
- name: "Initial ruby application"
  become: true
  hosts: centos7-test
  vars:
    ruby_app_environment:
      - name: SECRET_KEY_BASE
        value: "12345678"
      - name: RAILS_ENV
        value: production
      - name: RAILS_LOG_TO_STDOUT
        value: 1
      - name: DB_HOST
        value: 127.0.0.1
      - name: DB_PORT
        value: 5432
      - name: DB_NAME
        value: ruby_app
      - name: DB_USER
        value: ruby_user
      - name: DB_PASSWORD
        value: testtesttest

  roles:
    - ruby_app
